version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/python:3.6.1

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "requirments.txt" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirments.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirments.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd project
            python manage.py test
      
      - store_artifacts:
          path: test-reports
          destination: test-reports

